spring:
  profiles:
    include: local
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/codemia?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    hikari:
      data-source-properties:
        sslMode: REQUIRED
        enabledTLSProtocols: TLSv1.2,TLSv1.3
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

youtube:
  api-key: ${YOUTUBE_API_KEY:}
ai:
  anthropic:
    api-key: ${ANTHROPIC_API_KEY:}
  openai:
    api-key: ${OPENAI_API_KEY:}
  gemini:
    api-key: ${GEMINI_API_KEY:}
  groq:
    api-key: ${GROQ_API_KEY:}
cloudinary:
  cloud-name: daew3f0cq
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
piston:
  url: ${PISTON_URL:http://localhost:2000}
